# Generated by Django 4.2.2 on 2023-06-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_alter_projects_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="created_at",
            new_name="year_month",
        ),
    ]
